### ISSUE TITLE
[Feature request] Enable In-File search for PDFs

### ISSUE THREAD

**Issue by scambier** [scambier/obsidian-omnisearch#100]
Currently, In-File search is disabled for PDFs. Omnisearch can locate those files, but not open them at the correct position.

**Comment by sstar0016** [comment]
Could this also be extended to open images similarly? And if #65 is implemented could that also apply for images?

Would be really useful for something where there is a lot of writing on an image like below:
![image](https://user-images.githubusercontent.com/124852454/218215984-9a159d7c-4bb9-4bc3-bf7c-1f289eb51a60.png)

**Comment by 4Source** [comment]
Have the same problem. This would be great to have

**Comment by petergeneric** [comment]
To anybody else stumbling across this: this feature couldn't be implemented unless Text Extractor returns structured data with pages (ideally you'd need to know where in the page to go, in order to use Obsidian's PDF deep-linking).

Here's the feature request with Text Extractor https://github.com/scambier/obsidian-text-extractor/issues/75
