### ISSUE TITLE
[Feature Request] Display folder name/location

### ISSUE THREAD

**Issue by icebruce** [scambier/obsidian-omnisearch#107]
More of a nice to have feature, but it would be cool to see the folder name/location of the file. This is especially handy when the same search term appears in multiple files/context.

I know that by default Omnisearch shows the full path of the file, which provides for that level of detail. But I have it set to shortest path, as its easier to read and go through the list of results, (better UI/UX and less cluttered).

Proposed solution
![image](https://user-images.githubusercontent.com/66655064/195158914-06ef41bc-8431-402a-baa6-defaaa70680c.png)
Something like this is clean and neat, which is how [Another Quick Switcher](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher) is handling it 
![image](https://user-images.githubusercontent.com/66655064/195159715-c3474591-c430-4957-8ca8-c8e2e6fefcc0.png)

**Comment by charleshan** [comment]
I also came to say this. Another way to show the full path but still make the matching filename clear would be to add the full path in a separate line.

e.g. Instead of:
github/software/app/obsidian/scambier/obsidian-omnisearch/`[Feature Request] Display folder name/location`
Do this:
`[Feature Request] Display folder name/location`
github/software/app/obsidian/scambier/obsidian-omnisearch/

**Comment by scambier** [comment]
Deployed in beta, the layout has been updated

![image](https://user-images.githubusercontent.com/3216752/218269832-fe484b02-0534-4ff8-866b-4c2842850e9d.png)
