### ISSUE TITLE
[Feature request] Add recency (retrieval or last updated) to the algorithm

### ISSUE THREAD

**Issue by jamie9090** [scambier/obsidian-omnisearch#123]
**Is your feature request related to a problem? Please describe.**
I'm trying to replace the quick switcher with Omnisearch fully, but find sometimes a simple keyword like "prioriites" will show old docs that have high word frequency, rather than a more recent dock.

**Describe the solution you'd like**
I would love to be able to have a weighting for "recency" (either file opened, last modified or even retrieved via omnisearch). I feel this will bring Omnisearch closer to a full quick switch replacement, providing search + quick switching!

**Comment by scambier** [comment]
Interesting idea in theory, but will cause more problems than it solves because you're adding a seemingly random weight in the scoring. How would you alter the scores? How do you weight a perfect matching result opened 6 months ago against a mostly irrelevant note updated 10 minutes ago? Your definition of "recent" can be vastly different than someone else's.

I want Omnisearch to be predictable, and sorting results according to their last opened/updated/retrieved date is the opposite of that 🤷‍♂️. I said in a previous issue that Omnisearch is not Quick Switcher. They're similar, there's certainly an overlap in use cases, but if the results it yields are too broad, you should refine your query.

**Comment by jamie9090** [comment]
No problem, thank you!

If I could revise the wishlist request, it would be to bring date into the
query to use that as a way to refine search queries!

Cheers,
Jamie

**Comment by jessmartin** [comment]
This is something I'm looking for as well: show me the most recently opened or edited notes that match the Omnisearch query. I'm using Omnisearch as a straight-up replacement for Quick Switcher, so sometimes what I want is closer to Quick Switcher, but _actually searching the notes friggin' text_. Honestly, this should be the default behavior of Quick Switcher!

It would be really cool to be able to toggle between the two sorts: relevancy and recency.

A simple implementation that moves in the direction of the solution would be to show the last open/updated date in the search results, in the same way that you currently show "N matches."

**Comment by gratzel** [comment]
I really need this feature, too.  I have over 1000 notes, many of them work journals.  If I search for, say, "TPS report", I want to see results that were recently updated first in the list.  If Omnisearch always sorts for # of incidences, then some old note where I used the term a lot may always show up first, even if it is no longer relevant.
