### ISSUE TITLE
[Feature request] consider moving to uFuzzy

### ISSUE THREAD

**Issue by KraXen72** [scambier/obsidian-omnisearch#179]
**Is your feature request related to a problem? Please describe.**
https://github.com/leeoniya/uFuzzy is apparently faster & yields more results than minisearch.
see comparison:
https://leeoniya.github.io/uFuzzy/demos/compare.html?libs=uFuzzy,MiniSearch&search=super%20ma

**Describe the solution you'd like**
if not too much hassle, swap searching library to uFuzzy

**Describe alternatives you've considered**
continue using minisearch, as it is ok now.

**Additional context**
more info about uFuzzy in their readme

**Comment by scambier** [comment]
I can take a look to see how it performs (in terms of speed and quality) just out of curiosity, but unless I'm blown away by the results, there's little chance I'm going to replace Minisearch.

**Comment by leeoniya** [comment]
> but unless I'm blown away by the results

MiniSearch is one of the better ones (not super slow to search, no terrible matches, but startup indexing still takes 500ms vs 0.5ms for my 162k test dataset), so you won't be as blown away as someone coming from Fuse.

that being said, MiniSearch is quite bad outside of exact matches or exact prefixes. its `fuzzy` option brings back completely irrelevant results so is not good for typo tolerance. it also suffers from the same problem as many other searches -- it produces a single "score" that is then used for ordering. if we change uFuzzy settings to behave similarly to MiniSearch in terms of matching (outOfOrder, exact + prefixes), you can see how a slight change in its scores puts the results in :exploding_head: order. i don't think this is something that can fundamentally be fixed in most libraries that rely on composite relevance scores. you can read more thoughts about it here: https://github.com/leeoniya/uFuzzy#a-biased-appraisal-of-similar-work

https://leeoniya.github.io/uFuzzy/demos/compare.html?libs=uFuzzy,MiniSearch&outOfOrder&interLft=1&search=super%20ma

![image](https://user-images.githubusercontent.com/43234/214714114-e550a49c-f91e-43d5-a7c1-02a6d202e99f.png)

**Comment by leeoniya** [comment]
i tried your settings from

**Comment by scambier** [comment]
Thanks for those comments and clarifications. From your README:

> In its default configuration (uFuzzy) is likely a poor fit for applications like spellcheck **or fulltext/document search**.

For context, fulltext search is an important feature for me. My goal with Omnisearch is to allow retrieval of documents from queries that often don't match with filenames or headings. I need it to work in a "good enough" way for varied users who all use Obsidian differently; many of them have folders that contain thousands of (sometimes quite large) documents.

I see how your demo returns relevant results with shorter queries, but I'm mainly worried with the performances and results quality for all those users. Since Minisearch is at least "good enough" for them, I'm cautious about switching it for something else and breaking their workflow.

**Comment by leeoniya** [comment]
yep, no worries. :+1: 

for sure there's a tipping point when building an index is going to be more appropriate; "thousands of (sometimes quite large) documents" is definitely one of those cases. for fulltext search, you're better off stemming and doing spelling correction on the needle before continuing with efficient lookups in the index.
