### ISSUE TITLE
[BUG] Pdfs searching doesn´t work :-(

### ISSUE THREAD

**Issue by xverbatim1971** [scambier/obsidian-omnisearch#188]
unfortunately the plugin does not work.
i can't search pdf. i can't search text :-(
text extratcor is installed. pdf setting indexing on...
what am i doing wrong?

obsidian 1.1.9
installer version 1.1.8
win 10

thanks for the work on this plugin. i hope it works for me soon :)

**Comment by scambier** [comment]
When you right click on a PDF > Text Extractor > Extract Text into a new note, does it work?

Some files can't be extracted, but the most of them should work.

**Comment by scambier** [comment]
It creates a note that embeds the PDF. But it does also includes the text, right?

Like in this example with an image:
![image](https://user-images.githubusercontent.com/3216752/215543504-9414c307-dc4d-46d4-ab1a-7f6e9b797810.png)

**Comment by xverbatim1971** [comment]
no, not in my case.

i have a xyz.pdf and go to extract, then i have a new file with the name xyz without pdf extender. this is a normal pdf

**Comment by scambier** [comment]
Then that means Text Extractor did not manage to extract the text from your PDF, sorry 🤷‍♂️

**Comment by RuslansAleksejevs** [comment]
@xverbatim1971 
Hey, did you solve this problem at the end?

**Comment by xverbatim1971** [comment]
no, unfortunately I have not been able to solve the problem.

too bad...
it would be so important to be able to search pdf. 

i still hope for a development.

**Comment by RuslansAleksejevs** [comment]
@xverbatim1971 yeah, same. Damn, this plugin had one job...
Anyway, thanks for answering.

**Comment by scambier** [comment]
> @xverbatim1971 yeah, same. Damn, this plugin had one job...

Well you're welcome to help https://github.com/scambier/obsidian-text-extractor/discussions/21

If PDFs were easy to work with, Text Extractor wouldn't exist and Obsidian would have those features built-in. So yeah it fails with many files, but some is certainly better than none.

**Comment by RuslansAleksejevs** [comment]
@scambier Well, it certainly is better than nothing, if it does help someone and if people know that failed search means problems with extraction and not absence of searched text in the PDF (if the latter point is not satisfied, it is very harmful). 
For me, it did not work for any PDF files that I tried. Still, obviously, I appreciate your work, don't get me wrong.

Btw, since you are here:
1) Do I understand correctly that for it in order to be able to work one should enable both the Text Extractor plugin and the Omnisearch plugin **and nothing more**? Maybe it does not work for me, because I did not install something else. Tbh, necessary and sufficient set of software/plugins is not specified in repo's README.
2) It also would be very valuable to emphasize in README that even with everything correctly installed this plugin might not work. It would save a lot of time to users, since at the present in order to understand this fact one needs to scroll through issues, than scroll through closed issues and find there this specific issue (or one if its duplicates, which also would not exist, if it were written in README).

Thank you.

**Comment by scambier** [comment]
> it did not work for any PDF files that I tried

It's frustrating for both of us ^^

There's [this post](https://forum.obsidian.md/t/search-text-in-pdfs/511/40?u=scambier) on the Obsidian forum where I explained this:

_While there are ways to do this, solutions are often flawed: they break often, or don’t scale well, or take too much time/resources. The first version of Text Extractor used PDFjs and worked perfectly… unless you had more than a dozen files, then it hard crashed Obsidian._

> Do I understand correctly that for it in order to be able to work one should enable both the Text Extractor plugin and the Omnisearch plugin and nothing more?

Yep, one of the intended goals of Text Extractor is to be self-sufficient as a plugin. Text Extractor extracts the text (when it can...), and Omnisearch indexes the results.

> It also would be very valuable to emphasize in README that even with everything correctly installed this plugin might not work

You're right, that's not clear enough.

**Comment by xverbatim1971** [comment]
very sad that a pdf search does not work.
I have found a solution externally with the program FileLocator Pro / Lite it finds any text in a pdf file, so you can help yourself for now :-)
maybe obsidian will have a working pdf search soon - would be great :-)

**Comment by RuslansAleksejevs** [comment]
thanks, but search can be done externally even by Adobe Acrobat Reader, I really wanted something integrated into Obsidian
