### ISSUE TITLE
[BUG] No option to disable indexing notification.

### ISSUE THREAD

**Issue by szfkamil** [scambier/obsidian-omnisearch#209]
**Problem description:**
#91 shows there is 

https://user-images.githubusercontent.com/82778513/225296464-5708541d-4753-4cbc-95bf-7e4e9853f192.mov

an option for that, and yet, I don't have it on my Mac.

**Your environment:**
<img width="812" alt="Screenshot 2023-03-15 at 12 25 59" src="https://user-images.githubusercontent.com/82778513/225296528-cc036776-7143-4d05-9e0d-db5d1ad5cff6.png">
latest version, mac M1, latest version of Obsidian.

- Omnisearch version: 
- Obsidian version: 
- Operating system: 
- Number of indexed documents in your vault (approx.): 

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  
- Does the problem occur after a cache reset:

**Comment by scambier** [comment]
This option has been removed some time ago, because the only notifications that are shown are the important ones:

- The welcome message, displayed once right after installation/update
- The first indexing, which may take some time and impact performances
- When many files have been changed, same reason as above
- Change confirmation + reminder to restart Obsidian, for some settings

Aside from those rare notifications, Omnisearch should stay silent

**Comment by scambier** [comment]
It indeed does show 2 notifications when there's 1000+ files that need to be indexed (and when it's done, your screenshot). And it will reindex at each startup because in your case, caching is disabled. Did you disable it yourself (was there a problem?), or did it disable itself because it crashed?

I guess I could hide these notifications in this particular case.

**Comment by szfkamil** [comment]
ah! the cache...

all in all, IMO, it would be better to add the option back, perhaps with a warning (:

thanks for your help!
