### ISSUE TITLE
[BUG] Searching for path does not include any matches unless additional character is added

### ISSUE THREAD

**Issue by charleshan** [scambier/obsidian-omnisearch#240]
**Problem description:**

Searching for path does not include any matches unless additional character is added.

e.g. `path:"Zettelkasten/4. Permanent Notes "` should match all notes in this folder but nothing shows up unless I add something after a space: `path:"Zettelkasten/4. Permanent Notes a"`

**Your environment:**

Your environment:

Omnisearch version:
Obsidian version: 1.4.4 (API v.1.2.7)
Operating system: Android
Number of indexed documents in your vault (approx.): 3000

**Comment by scambier** [comment]
`ext:` and `path:` are meant to restrict the number of results, they're not really part of the query

**Comment by charleshan** [comment]
I see that but isn't what I've described above the expected behavior?

**Github Issues**
`is:issue is:open` shows all open issues.

**Obsidian Search**
`path:"Zettelkasten/4. Permanent Notes"` shows all notes in the folder.

**Calibre Search**
`formats:"=EPUB"` shows all files with EPUB format.

Just to name a few... If you don't see this as a bug, I guess we can call it a feature request.

**Comment by scambier** [comment]
Omnisearch will find and rank files based on search tokens. Additional fields like `ext:` or `path:` only refine those results. If you specify only e.g. `path:`, there's no result to refine.

The behavior you expect would completely bypass Omnisearch's main feature. I'm also not sure of the added value this would bring: is it useful to list all files from a folder in Omnisearch, which can also be done way faster by clicking on said folder instead of typing it?
