### ISSUE TITLE
[Feature request] Paragraph retrieval and Latex searching

### ISSUE THREAD

**Issue by sivecow** [scambier/obsidian-omnisearch#242]
**Is your feature request related to a problem? Please describe.**

I frequently use Obsidian for taking math notes, and I sometimes encounter the issue of having to repeat definitions and theorems that I've previously documented. Over time, I tend to forget what I've written before, resulting in redundancy in my notes. Moreover, there are instances where I come across two theorems with similar assumptions but different conclusions, and it would be beneficial to locate them quickly to make necessary modifications.

**Describe the solution you'd like**

I would greatly appreciate it if the search engine could perform paragraph retrieval, meaning it would retrieve and rank the relevant paragraphs. Typically, paragraphs are separated by two consecutive line breaks. Furthermore, it would be highly valuable if the search engine could also search for mathematical formulas, similar to the capabilities offered by tools such as [Approach Zero](https://approach0.xyz/search/) or [SearchOnMath](https://www.searchonmath.com/).

**Comment by scambier** [comment]
Won't fix, sorry.

Due to the way Omnisearch works, math formulas can't be correctly indexed; it's definitely not the right tool for the job, I think the core search is better suited. As for paragraph indexing, I get the use case, but IMO it's not worth the additional (maintenance) work on top of Vault Search and In-File Search
