### ISSUE TITLE
[Feature request] Ability to search video filenames

### ISSUE THREAD

**Issue by leonlazic** [scambier/obsidian-omnisearch#254]
What I am missing is the ability to search for any file name in my vault. Even ones, where contents can't be indexed, like video files for example. 
Currently if I add a .mp4 or .mov extension to "Additional files to index" option in the settings, the app starts crashing as warned with the Office file extensions.
What I would like is just to find the file name with Omnisearch (similar behaviour to when searching the .pdf file name). The default open file command in Obsidian does that for all file extensions but I would like to have that in my **OMNI**search 🙂.

**Comment by scambier** [comment]
Instead of supporting a static or user-customizable list of files, I'll do it like this:
![image](https://github.com/scambier/obsidian-omnisearch/assets/3216752/ae6d6342-b04c-4d27-a8f7-60a75cb40657)

Omnisearch will simply index _all_ files, and if it can't read their contents, only the filename will be indexed.

**Comment by leonlazic** [comment]
That would be amazing and just what I was hoping would be done.

**Comment by scambier** [comment]
Deployed in 1.15.0-beta.2
