### ISSUE TITLE
[BUG] `path:` in search does not work when the path has capitalization

### ISSUE THREAD

**Issue by Florian-Laport** [scambier/obsidian-omnisearch#294]
**Problem description:**

When paths have uppercase letters and I try to select for them with `path:` in Omnisearch, there are no results.
In all other cases, `path:` works fine. I tried to find other Unicode codepoints that might produce the same issue, but uppercase characters seem to be the only offending party.

**Your environment:**

- Omnisearch version: 1.15.2
- Obsidian version: 1.4.13
- Operating system: Arch btw
- Number of indexed documents in your vault (approx.): ~1700

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  Yes
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  Yes
- Does the problem occur after a cache reset: Yes

**Comment by scambier** [comment]
I'll need a reproducible example for this one, because it works for me 🤷‍♂️
![image](https://github.com/scambier/obsidian-omnisearch/assets/3216752/cec7c3c8-dc82-4634-ba00-cbe2750dcf5f)

The path is transformed to lower case when it's checked
https://github.com/scambier/obsidian-omnisearch/blob/5066b019c5e00d656ce87dc4d452e6c662782c7c/src/search/omnisearch.ts#L236-L237

**Comment by Florian-Laport** [comment]
I think I see the problem. The behavior seems to be different when using quotes.
I have a directory `Archive` which I can match with `path:Archive`, `path:archive`, and `path:"archive"`, but **not** with `path:"Archive"`.

**Comment by scambier** [comment]
Still works as expected for me :/

Can you reproduce it reliably with any note or folder?

**Comment by Florian-Laport** [comment]
Apparently I wasn't on latest version, and I don't have this bug in `1.17.1` anymore ¯\_(ツ)_/¯
