### ISSUE TITLE
[Feature request] or [Question] How to inject omnisearch results into https://start.duckduckgo.com or other search engines?

### ISSUE THREAD

**Issue by merlinuwe** [scambier/obsidian-omnisearch#308]
Thanks for your great plugin.

I have installed and configured Tampermonkey, following this: https://publish.obsidian.md/omnisearch/Inject+Omnisearch+results+into+your+search+engine and it works great with 

https://google.com
https://www.google.com
https://google.de
https://www.google.de/

Then I tried to ad

https://start.duckduckgo.com
https://duckduckgo.com

![image](https://github.com/scambier/obsidian-omnisearch/assets/4138869/69b88b04-f456-48c7-b800-2c354e88e8a0)

What can I do to configure it to work with https://start.duckduckgo.com/ or https://duckduckgo.com/ or other search engines?

**Comment by scambier** [comment]
Omnisearch's API only returns a raw json array, and it is the userscripts' responsibility to format this data into HTML that fits the site's structure and style, and inject it at the right place. So just like there is a specific Omnisearch script for [Google](https://github.com/scambier/userscripts/blob/master/dist/obsidian-omnisearch-google.user.js) or [Kagi](https://github.com/scambier/userscripts/blob/master/dist/obsidian-omnisearch-kagi.user.js), you'll need a script specifically crafted for DDG.

If you know a bit of javascript and know how to use your browser's dev tools, you could try yourself to modify the Kagi script for DDG :)

Otherwise I'll work on it as soon as I got the time 👍

**Comment by merlinuwe** [comment]
> Otherwise I'll work on it as soon as I got the time 👍

I'm no software developer, so thank you so much for this offer. ;-)

**Comment by scambier** [comment]
https://github.com/scambier/userscripts/raw/master/dist/obsidian-omnisearch-ddg.user.js :)

**Comment by merlinuwe** [comment]
Thank you sooo much! It works!
