### ISSUE TITLE
[BUG]  Search fails…

### ISSUE THREAD

**Issue by DaHunch** [scambier/obsidian-omnisearch#331]
**Problem description:**

https://www.reddit.com/r/ObsidianMD/s/rnhSq62mSS
This has a video of the problem in action. Lots of people reporting similar issues….

Am using latest version of Omnisearch on a MacBook Pro running latest OS. Many thanks!!

**Comment by scambier** [comment]
Does searching for `will self` (without quotes) still return the "notable agnostics" note, but lower in the results? If you have several notes containing both words more prominently (i.e. in titles), they'll be ranked higher.

Regarding `"will self"` (with quotes), it looks like a bug. Does it work after a restart?

Could you also check the dev tools (option+cmd+i on Mac I think) if there are any logged errors? Thank you :)

**Comment by DaHunch** [comment]
Hi Simon - no, without quotes returns nothing from the Agnostics note, however far down I scroll.
Tried again with quotes and no, sadly I get nothing from that at all.
I've managed to get the Dev Tools window to open on the right of the app, but sorry, you'll need to tell me where to look for any logged errors. Nothing immediately apparent from clicking on a few menu items….

**Comment by scambier** [comment]
Can you find that specific note with another search query?

For the logs, the important part is here, errors are in red.
![image](https://github.com/scambier/obsidian-omnisearch/assets/3216752/690615f1-d0ff-45b4-b4ac-dcb0a420ff5f)

If there are no errors, I suggest cleaning the Omnisearch cache and restarting Obsidian to see if it helps.
![image](https://github.com/scambier/obsidian-omnisearch/assets/3216752/07bb9739-726f-4990-95ad-0f7b85cf1a6d)

**Comment by DaHunch** [comment]
Well - it's really bizarre.
I can't see any errors - here is my log:
![image](https://github.com/scambier/obsidian-omnisearch/assets/135022979/688aefc2-2d2a-40f1-a4b9-c0af3f4c72e6)
I've now written the term `Will Self` in about 3 different notes, and it doesn't return any of them.  To answer your question, yes, other search terms are returned from that Agnostic note, no problem.
I cleared the cache in settings and restarted, and after re-indexing etc. the exact same problem still exists…

**Comment by scambier** [comment]
> I've now written the term Will Self in about 3 different notes, and it doesn't return any of them. To answer your question, yes, other search terms are returned from that Agnostic note, no problem.

Ok _that_ is bizarre 😅

Could you try opening the default "Help" Obsidian vault, put your "notable agnostics" not in there, and reproduce the issue?

**Comment by DaHunch** [comment]
Ok. I set up the Sandbox vault (I assume that's what you meant) and copied over the note. Plus littered a few more 'Will Self' references in other new notes. Installed Omnisearch, and it all worked fine.

By the way - just for the record - back in my vault, Obsidian's native search find the 3 references in my vault to "Will Self' absolutely fine… as shown here

<img width="269" alt="image" src="https://github.com/scambier/obsidian-omnisearch/assets/135022979/a9c64618-9bde-4180-831e-db07bf071b61">

But Omnisearch still only finds the one note where "Will Self' is in the actual title of the note

<img width="728" alt="image" src="https://github.com/scambier/obsidian-omnisearch/assets/135022979/54f6ea9b-fe83-4e02-aae2-b8486eaf24d3">

**Comment by scambier** [comment]
Thank you.

I'd like to rule out a conflict with another plugin. Could you:
- Try to reproduce the issue with all other community plugins disabled
- (or) create a new clean vault with all your notes, install omnisearch, and check if it works

All while keeping an eye on the console log for any error that might pop up.

If the issue still persists, I can only guess there's a document in your vault that breaks indexing or searching :/

**Comment by DaHunch** [comment]
Ok - disabled every single plugin apart from Omnisearch - and sadly it still behaved in exactly the same way.
Not au fait with programming etc. so don't understand how a document could 'break' indexing/searching - so I guess three questions:

- how do I hunt that document down?
- why does it not 'break' Obsidian's core search functionality?
- how does one ensure that a document doesn't break Omnisearch in future?

thanks!
Patrick

**Comment by scambier** [comment]
> how do I hunt that document down?

Tediously. Start a new vault, install Omnisearch, add documents folder by folder until it stops working. Then remove document by document until it works again.

Honestly I'm not even sure the bug is triggered by a specific document, it's just my best guess.

> why does it not 'break' Obsidian's core search functionality?

A better question is "why does it break Omnisearch", and 🤷‍♂️

Unless I can reproduce the bug reliably and find the root cause, it's guesswork.

**Comment by DaHunch** [comment]
Ok - I'm very (very) folderless - so 95% sure it will be in my main one, and therefore would be a struggle to drill down on this issue!
Let me think about sharing the vault. I'd love to help if it helps Omnisearch become an even better product! Can I ask, is there any way you could do what you need to do via a remote link?

**Comment by scambier** [comment]
It would be complicated, as I'd make incremental changes on the source code with continuous recompilations, probably try older versions of Omnisearch, and add/remove files from the vault. Again, no worry; I just had to ask, it's 100% fine to refuse.

I'll think a bit more about the issue and will work on a custom build, maybe next week. I'll tweak it to log the relevant information 👍

**Comment by DaHunch** [comment]
Ah - ok. Yeah - sorry, I think I'll keep the vault private. Paranoia!

BTW - just tried changing the last letter in the text string so it read "_Will Sele_" and then also _"Will Selg_". In both cases Omnisearch found all instances of it! But then, back to _Will Self_ and it fails again.

Would be fascinated to see if you manage to work out what's going on…

Many thanks for taking such an interest. I love your creation in every other way!

**Comment by scambier** [comment]
_The plot thickens._

Does it also work with `will sel`?

A random idea: could you try adding the word `shelf` (or `will shelf`, or any random word ending in `f`) in a few notes and check if they're correctly returned in results? I'd like to know if it's reproducible with something else than `will self`.

> Many thanks for taking such an interest.

That's a breaking bug that I don't understand, of course it's interesting :D

>I love your creation in every other way!

Thanks :)

**Comment by DaHunch** [comment]
No - Will Sel does not work either, nothing found via Omnisearch.
But Will Shelf works fine, as does Will Xelf…

**Comment by DaHunch** [comment]
Hi Simon

Hope you’re doing well.

Another strange thing I’ve noticed about how Omnisearch behaves, at least for me.

Sometimes if I type too much I lose what I’m searching for.

I’m looking for my notes on a book called ‘The End of Procrastination’. If I just type ‘The End of’ - it shows top of the list. If I type just one more letter, ie. ‘The End of P’, bang - it’s gone. Whereas I would have expected it to solidify its position in first place!

Hopefully the attached video demonstrates it. 

￼

Any thoughts?

Many thanks!

Patrick

**Comment by scambier** [comment]
Sorry, the video still doesn't work.

Does the expected result finally show up when you keep typing more chars for "procrastination"?

**Comment by DaHunch** [comment]
How weird - I see the video fine.

Anyway, no matter.

I did a spreadsheet to show you exactly what happens as I progress through typing 4 - 15 characters that exactly match the title.



https://docs.google.com/spreadsheets/d/1KyZlTwVDfHndGQMBR7b9INrGiWI93Lsvfr8Mh0S6moU/edit?usp=sharing￼
Omnisearch
docs.google.com

**Comment by scambier** [comment]
Thanks for that detailed report :)
The fact that you don't even have a single result while searching for "The" doesn't make any sense :/

Could you
- Create a new blank vault in a directory that is outside of any syncing solution (i.e. **no** dropbox, google drive, syncthing, ...)
- Copy all your documents inside it. _Only the documents_, don't copy the `.obsidian` folder or any other folder starting with a `.`
- Install Omnisearch as the only plugin
- Check if the issue persists

**Comment by DaHunch** [comment]
Sorry - just to clarify, when I say 0/50 - I mean that particular file doesn’t feature anywhere in the top 50 results.

1/50 means it came 1st, 35/50 means it was in 35th position.

Just so peculiar that it hits 1st place with 8 characters, but sinks to 16th with 9!

Anyway - shall try your set of instructions….

P.

**Comment by DaHunch** [comment]
Ok - updated the spreadsheet with the results from the new test vault.

SO bizarre.

It actually got worse… taking 16 characters until I got it to hit no. 1 in the search results….

**Comment by scambier** [comment]
I stand by my initial guess that something in your vault is corrupting the search 😕 I'm sorry I can't help, since I'm unable to reproduce any of the described behaviors on my test vaults.

If you're willing to dig more yourself, you could start with an empty vault, start with your note "📖 The End of Procrastination", add x files at a time, and check how Omnisearch behaves between each batch. Once it starts breaking, bisect the last batch until you find the offending file - if that's indeed the cause.

Again, I'm sorry I can't fix this.

**Comment by DaHunch** [comment]
Ok - I’ve pared the vault down to 300-odd files which I’m ok to share with you.

And the issue is still an issue, even with that number.

By the way - the Will Self issue is still a factor as well! (typing Will_ makes it to number 2, typing Will_S sees it drop to no. 40-odd!).

Would you like me to share the vault? It’s about 2mb.

If so - what’s the best way?

P.

**Comment by scambier** [comment]
_Copy-paste from my email answer:_


From your spreadsheet (I've added line numbers)

1 | The_End_ | 8 | 2/50 |   | Still 2nd
-- | -- | -- | -- | -- | --
2 | The_End_o | 9 | 32/50 |   | SO ODD!
3 | The_End_of | 10 | 3/50 |   | Back in the frame
4 | The_End_of_ | 11 | 3/50 |   | Still 3rd
5 | The_End_of_P | 12 | 0/50 |   | What?

Here's what's going on:

1. When you search for "The end", Omnisearch will find all notes containing those words, or words that begin with those prefixes (like "theft" or "ending"). Your note "The end of procrastination" has both whole words in its title, it scores many points, and is returned 2nd
2. You add "o" to the search, and this changes everything: all notes that contain words beginning with "o" suddenly score higher because each of those words will slightly bump up their ranking. Your note "The end of procrastination" also has a higher score, but is still outranked by all the notes containing many "o..."
3. Same logic as 1: whole words in the title, bump to the 2nd place. Note that it's still outranked by "How to take smart notes", probably because it contains a ton of "the..."
4. Same as 3, spaces don't count
5. Same logic as 2, the lone "p" will bump all the notes that contain words beginning with p


"Will Self" suffers from the same problem; it's a relatively short note that's easily outranked by larger ones, because they score more small points. Death by a thousand cuts.

Searching with quotes might not help, because this will only refine the top 50 results. So if the note you're looking for is not at least 50th, it won't show up at all.

**Comment by DaHunch** [comment]
Hi Simon

Thanks! Sorry - been away for a few days.

Wow - that’s great to understand it so much better - and I feel really bad for your time I’ve taken when actually all I needed to do was understand the raw mechanics of what Omnisearch prioritises. I also realise that when I’m looking for my tally of questions and tasks for Obsidian, all I do is search for 'Obs Q’ and bang, top of the list it returns my note with the title Obsidian to do's & questions which is great.

Thanks again for all your help and I’ll leave you in peace.

Cheers

Patrick

p.s. congrats on winning the 2023 Plugins Gems award!

**Comment by scambier** [comment]
Don't worry, it only became obvious when I started typing your queries 👍

> p.s. congrats on winning the 2023 Plugins Gems award!

Thanks!
