### ISSUE TITLE
[BUG] I don't thnk indexing is actully happing 

### ISSUE THREAD

**Issue by the1gofer** [scambier/obsidian-omnisearch#368]
I keep getting the popup that says  many files need to be indexed and that it may cause isues with obsidian wile that happens, and while I'm having the suttering, the number never seems to go down.  Is there any way to see if indexing is actually happening, or is stalled?

**Comment by scambier** [comment]
When you created this bug, there was a template to fill that asked a few important questions, such as:
- Operating system: 
- Number of indexed documents in your vault (approx.): 
- Does the problem occur when Omnisearch is the only active community plugin:  
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  

You should make sure that "Save index to cache" is enabled, if you're not on iOS. After that, restart Obsidian and let Omnisearch do the indexing. There will be another notification that will tell you "Your files have been indexed" once it's done. The Omnisearch modal will also display a message when you open it while indexing is still running.

It's important to let it run fully, otherwise the cache won't be written

**Comment by the1gofer** [comment]
thanks for the response.  It seems like the indexing is done, (no
stuttering), but the modal never says completed.

Jason Crews
