### ISSUE TITLE
Complex queries with OR/AND etc operand within the HTTP Server + other API Improvements

### ISSUE THREAD

**Issue by 8times4** [scambier/obsidian-omnisearch#420]
**Is your feature request related to a problem? Please describe.**

Currently the API server only allows handling of string queries without any OR/AND operand.
API server also has no option to define an API key, or port to be used. (API key would allow "some" protection towards the vault, although not even sure if that's useful)

**Describe the solution you'd like**

An optional flag for complex query parsing or straight up parsing it with the same method that happens within Obsidian UI. 
An option to set both an API key and IP.

**Describe alternatives you've considered**

Simple queries will not let me use the API with OR/AND etc, so not really an option.
API Key and IP are not really necessary but I believe it'd offer some advantage with not a lot of work.

**Additional context**

This is how I've implemented the API stuff in my demo code:
<img width="788" alt="image" src="https://github.com/user-attachments/assets/a5a8adb7-1ac2-4722-8fde-0fae3a99eb7d">

Thank you!

**Comment by scambier** [comment]
Omnisearch itself does not support operands, by design. Advanced queries are better handled by the core search feature of Obsidian.

For the API HTTP server itself, you can set the port in the settings, and the IP is configurable directly in the settings file https://github.com/scambier/obsidian-omnisearch/issues/396#issuecomment-2357629164

For the same reason that the IP setting is hidden and prefixed with `DANGER_`, I'm also quite lukewarm to the idea of an API key. It sets an expectation of security, and I don't want to have that responsibility 🤷‍♂️

**Comment by 8times4** [comment]
> Omnisearch itself does not support operands, by design. Advanced queries are better handled by the core search feature of Obsidian.
> 
> For the API HTTP server itself, you can set the port in the settings, and the IP is configurable directly in the settings file [#396 (comment)](https://github.com/scambier/obsidian-omnisearch/issues/396#issuecomment-2357629164)
> 
> For the same reason that the IP setting is hidden and prefixed with `DANGER_`, I'm also quite lukewarm to the idea of an API key. It sets an expectation of security, and I don't want to have that responsibility 🤷‍♂️

Ugh, my apologies, this was beyond skill issue tbh.. I should've versed myself much better with Obsidian and your docs before asking stupid questions. 

Thanks for the reply, have a nice one!
