### ISSUE TITLE
[Feature request] Index text without diacritics

### ISSUE THREAD

**Issue by Sanqui** [scambier/obsidian-omnisearch#53]
When I search for "zlutoucky", I would like to be able to find "žluťoučký", and vice versa.  These results should have a lower relevancy/priority.  Would this be possible?

**Comment by scambier** [comment]
Omnisearch would have to index an additional computed field to hold the converted text without diacritics. Definitely doable, but I'd put that behind a setting, since that would roughly double the indexing duration and increase memory consumption.

I'm not sure how it will work with the in-file search, but I can take a look at it. Anyway, this part needs a rework.

> These results should have a lower relevancy/priority

Because the same word with and without diacritics could have 2 different meanings?

**Comment by Sanqui** [comment]
I don't mind it being behind a setting.  It's too bad you may have to convert the text, would be nice if the search library you're using offered diacritics removal alongside stemming possibly lemmatization.

>>These results should have a lower relevancy/priority
>Because the same word with and without diacritics could have 2 different meanings?
Indeed, many such cases.  Though I would have to see it in practice to know if it would be usable if the results were ranked the same, I suspect it would be only a minor annoyance.

**Comment by scambier** [comment]
> It's too bad you may have to convert the text, would be nice if the search library you're using offered diacritics removal

Well, I suspect it's specifically _because_ diacritics can change the meaning of a word. I have the same issue in French, but to a lesser degree: the fuzzy matching usually works around it ("creme brulee" will match "crême brulée").

I think that a better solution would be a toggle to simply ignore diacritics: normalize all search queries, and notes before indexing.
