### ISSUE TITLE
[Feature request] Search should also find non-md files (most importantly pdf)

### ISSUE THREAD

**Issue by matthiashaldimann** [scambier/obsidian-omnisearch#58]
Problem:
The internal search allows you to find and open pdfs and other non-md files using keywords from their filename.

Solution:
As the default search of Obsidian, Omnisearch should find non-md files when the typed keyword is part of their filename. Enter opens them. (The perfect solution would be to also index the content of pdf files ;-)).

**Comment by scambier** [comment]
Indexing PDFs is a long-term feature I'd like to implement :)

**Comment by jeffkimbrel** [comment]
Some of use are using the [txt-as-md-obsidian](https://github.com/deathau/txt-as-md-obsidian) plug-in to make files that are plain text but not `.md` files appear in obsidian (I mostly use `.rmd` and `.qmd` files). Although this works and this files to appear (and are editable) in obsidian, they are not visible in the search (https://github.com/deathau/txt-as-md-obsidian/issues/1#issue-901311966). 

It would be great if omnisearch could add that functionality. Just throwing my two cents in extending this enhancement to other file types beyond pdf. Since they are also just plain text, maybe it is even easier?

Thanks!

**Comment by scambier** [comment]
@jeffkimbrel 

Added a new feature & setting to index plaintext files that are not markdown. This change should also make the plugin "txt-as-md" redundant, since Omnisearch itself will register `txt` (and other) files.

![image](https://user-images.githubusercontent.com/3216752/192037897-3146de9d-0be3-4d71-b0ca-8f387d926796.png)

This change is deployed in 1.6.0-beta3, if you'd like to try it.

**Comment by matthiashaldimann** [comment]
Thank you very much, works as expected! Looking much forward to pdf indexing ;-).

**Comment by jeffkimbrel** [comment]
Awesome, this is great. Thanks so much!!

**Comment by scambier** [comment]
PDF support has been added in the latest beta build. There are a few bugs to iron out, but it's a start.

Don't hesitate to post feedback here 👍

**Comment by scambier** [comment]
The feature is now published. It's not 100% complete yet, follow-up at #100

**Comment by scambier** [comment]
Update - Omnisearch no longer registers the other files itself. It still indexes them, but Obsidian's behavior is respected, and the files will open in an external application by default. You may want to use another plugin (like [plaintext](https://github.com/dbarenholz/obsidian-plaintext) for example)

**Comment by scambier** [comment]
There's a random Electron crash during PDF indexing, this change is reverted.

**Comment by scambier** [comment]
Re-deployed as a BRAT beta version. Will need more feedback before this can go into release.

**Comment by tekwizz123** [comment]
Seems like downloading the files is considerably slow and does freeze Obsidian. It might be advisable to see if there is a way to do this in the background so that the main app is still responsive.

Searching is slowed down a little bit when searching with PDFs however whilst noticeable with my vault of about 1450 notes it wasn't noticeable enough to be anything more than a minor inconvenience.

Searching inside of PDFs also appears to be working. Here I am searching for the first few words of the first paragraph in the PDF and this is finding a hit, albeit it isn't shown in the search results which is a little confusing:

![image](https://user-images.githubusercontent.com/2746189/194733801-a2deb1e9-f026-45c5-93a5-72cd6b4a53c2.png)

This was done using all recommended settings, OmniSearch 1.6.5 Beta, and Obsidian 0.16.5 with the following plugins installed:

- Annotator 0.2.6
- AutoMoc 1.1.1
- Calendar 1.5.10
- DataView 0.5.46
- ExcaliBrain 0.1.11
- ExcaliDraw 1.7.22
- File Explorer Note Count 1.2.0
- Find orphaned files and broken links 1.8.0
- Homepage 2.2.1
- Note Refactor 1.7.1
- Obsidian42 - BRAT 0.6.35
- Omnisearch 1.6.5-beta
- Raindrop Highlights - 0.0.14
- Templater - 1.14.3

Default theme was used in case that helps (doubt its relevant here though).

Total of 31 PDFs were in the vault I used for testing.

Loading delay and freeze was about 2-3 minutes.

**Comment by tekwizz123** [comment]
Upping sample size to 231 PDFs whilst also not including the "Store Index in File" part produced similar results although this time I did get a warning from the plugin. It does disappear a little fast for my liking and only appeared for about 3-5 seconds so you do have to be quick to notice it.

Testing with 1000 files went over 200 seconds before I stopped counting. The left side of the screen on the file navigation bar would go in and out of being interactable but I was never able to use it to open any files.

Looking at task manager showed that Obsidian was stuck at somewhere between 37 and 45 percent CPU usage with about 700 to 1GB of memory usage.

I thought this may be due to using Synology Drive to sync the files so I paused that thinking it might allow the files to process quicker, as I did see SearchFilterHost.exe using about 30% CPU at times however this didn't change things.

When I finally did get control back it was about 5-8 minutes later, perhaps longer.

There should likely be a limit on the number of files or some way to cause this processing to occur in the background to prevent it freezing Obsidian itself.

Overall though I think this is a great addition, nice work! Just need to figure out how to optimize it to handle big PDF collections a bit better as it seems fine at lower PDF numbers but once the count goes up it becomes problematic.

**Comment by tekwizz123** [comment]
Sorry realized the timing info earlier wasn't helpful so here is a quick update:

Using 967 PDF files with  "BETA - Index PDFs" and "Store Index in File" takes 8 minutes. Without the "Store Index In File" was a similar time of about 7 min 50 seconds.

**Comment by scambier** [comment]
@tekwizz123 Thanks for the feedback 👐 The indexing is already done in the background, so I'll split the indexing into smaller chunks to ease the CPU usage.

> Searching is slowed down a little bit when searching with PDFs

Indexing a PDF is done in 2 phases:
- First the text is extracted. That what takes time, and slows Obsidian.
- Then the text is indexed in memory, just like a normal note.

So the search time shouldn't be impacted.

> Searching inside of PDFs also appears to be working. Here I am searching for the first few words of the first paragraph in the PDF and this is finding a hit, albeit it isn't shown in the search results which is a little confusing

I noticed some search results issues too, I'll have to check if it's relative to PDFs or a more general bug 👍

**Comment by scambier** [comment]
Beta update: https://github.com/scambier/obsidian-omnisearch/releases/tag/1.6.5-beta.3

PDF indexing is now correctly done in the background, and results are directly cached. You can safely close Obsidian even if the work is still in progressed, it should just resume where it left.

**Comment by scambier** [comment]
Alright, PDF now also works on mobile. Unless some breaking bug is discovered by then, I'll release this feature by the end of next week. @tekwizz123 I'd be very thankful if you could put a stress test on it with your thousand PDFs :)

**Comment by tekwizz123** [comment]
@scambier Thanks, upgrading and testing this out now 👍

**Comment by tekwizz123** [comment]
Still hitting some issues. Initially delays were only 2-5 seconds however now they are getting longer. Generally delays are consistent in time however the more concerning part is that the left hand pane for file navigation can stop responding at times. If this was just it that would be fine however when I right click on a file in the list and try to open it I just get this:

![image](https://user-images.githubusercontent.com/2746189/196006253-074fd4f2-0c03-42a1-9162-a03020600c3f.png)

I also tried opening other files normally and got similar results. Opening up a Annotator file had PDF.js error out the first time, then the pages just showed up as blank/white pages after that.

**Comment by tekwizz123** [comment]
For reference this was with a heavy stress test of just under 5000 files.

**Comment by scambier** [comment]
Thank you. In the folder `.obsidian\plugins\omnisearch`, you should find a file named `pdfCache.data`. Could tell me its size?

**Comment by tekwizz123** [comment]
Oops, looks like now Obsidian is black screen of deathing on me 😨 

![image](https://user-images.githubusercontent.com/2746189/196006385-32a7d0fa-cad7-4d1e-aba8-f2c1fd76fb54.png)

**Comment by tekwizz123** [comment]
> Thank you. In the folder `.obsidian\plugins\omnisearch`, you should find a file named `pdfCache.data`. Could tell me its size?

Huh I'm not seeing a file with that name, here is what I see:

![image](https://user-images.githubusercontent.com/2746189/196006415-514f0494-2d5f-41be-b453-1f38d4f20b57.png)

**Comment by scambier** [comment]
> > Thank you. In the folder `.obsidian\plugins\omnisearch`, you should find a file named `pdfCache.data`. Could tell me its size?
> 
> Huh I'm not seeing a file with that name, here is what I see:
> 
> ![image](https://user-images.githubusercontent.com/2746189/196006415-514f0494-2d5f-41be-b453-1f38d4f20b57.png)

🤔 The indexing is now done 100% in the background. The only task susceptible to freeze Obsidian is the cache file writing. It's throttled but I think it's just too big for the throttling delay, and it keeps overwriting itself - which explains why it's getting worse with time, since it's getting larger and larger. I was planning to do a cache refacto for the next version, but I'll have to do that sooner 😅

Thanks again, your stress tests are definitely helping me!

**Comment by tekwizz123** [comment]
@scambier For reference would that cache writing be affected by any settings? I did try disable the use of the cache/index file in the settings but still getting that issue when trying to open new files as well as the delay mentioned earlier.

**Comment by scambier** [comment]
@tekwizz123 
> For reference would that cache writing be affected by any settings

No, extracted texts from PDFs are automatically saved in their own cache. Extraction is slow and eats a lot of CPU, so it'd be unusable without a cache.

**Comment by scambier** [comment]
I released a new beta version, the PDF cache is now handled by IndexedDB.

I ran some tests, and the only stutters left are caused by minisearch when indexing _big_ files (e.g. ebooks). I'll look if I can defer that to a worker, but it's doubtful. Those stutters disappear when the "write index on disk" setting is enabled.

I think there's 0 chance that indexing 5000 PDFs is going to be 100% smooth, but I did everything I could to make it not crash :D

**Comment by gwillcox-r7** [comment]
Thanks @scambier (sorry writing from work account). I agree 5000 PDFs will never be 100% smooth was more testing for edge cases there like the crashes we experienced 👍 I'll see how this goes though with the new update :)

**Comment by gwillcox-r7** [comment]
> Do you happen to know where I could download a bunch of different PDFs? It would be more effficient (and less annoying for you) if I could stress test myself.

Sure, see https://corpora.tika.apache.org/base/packaged/pdfs/archive/pdfs_202002/ which has a nice corpus of tests for testing PDF parsers.

**Comment by gwillcox-r7** [comment]
Also more info at https://www.pdfa.org/stressful-pdf-corpus-grows/ if you want to see the related document listing more details on this.

**Comment by scambier** [comment]
Alrighty, the bug was found and promptly squashed: I was spawning too many web workers, and Electron did not like that. And guess what? _Now it's smooth_. It crunches through 990 PDFs like nothing: it took 8 minutes to index everything with a pool of 10 web workers.

![image](https://user-images.githubusercontent.com/3216752/196534269-a3f2d04e-63dc-4242-86aa-e6b9d406d5a5.png)

The latest beta will be deployed in a few minutes 🚀

**Comment by tekwizz123** [comment]
Alright 4900 PDFs processed in about 1 hour 11 min. Not bad 👍

**Comment by tekwizz123** [comment]
Alright one thing I did find is I did get a crash later when trying to search through the documents for various things. Did about 4 searches and then was trying to type out one search and Obsidian black screened in the middle of that.

**Comment by scambier** [comment]
This should unstuck you:

- Close Obsidian
- Go in `.obsidian/plugins/omnisearch`
- Delete `data.json` to reset Omnisearch settings to defaults
- Delete all `*.data` files to remove the cache
- Start Obsidian

If you happen to reproduce a crash, could you please tell me:

- Is the cache writing enabled
- What query were you typing

If the PDF indexing reached completion, then I'm almost certain the issue is triggered by another part of Omnisearch; either the cache writing (volume too large & throttling too short), or a crash during the search/results generation.

I'll run more tests with more PDFs and finish the cache refactor.

**Comment by scambier** [comment]
So.

I published 1.7 with PDF indexing, but removed the cached index. I will probably reimplement it later (#92).

**Comment by tekwizz123** [comment]
@scambier Latest 7.3 seems to be consuming 3700 PDFs at a rather respectable 28 minutes or so, working quite well 👍
