### ISSUE TITLE
[Feature request] Store notes cache index to the file to avoid reparsing

### ISSUE THREAD

**Issue by mnaoumov** [scambier/obsidian-omnisearch#62]
**Is your feature request related to a problem? Please describe.**

I have a big vault with ~40k notes. Recreating an index on each Obsidian open is an unnecessary massive heavy operation.

**Describe the solution you'd like**

I suggest to store cache index to the external file so it could be imported without reindexing all the notes. Probably there should be some additional mechanism to catch notes changed since cache index was saved. It could be just notes last modified date.

**Describe alternatives you've considered**

[Everything 1.5](https://www.voidtools.com/forum/viewtopic.php?f=12&t=9793)

**Additional context**

N/A

**Comment by scambier** [comment]
Ha, I was saying 2 days ago to another user that nobody complained about indexing time, so there was no need to save the index yet :D

**Comment by mnaoumov** [comment]
@scambier My 40k notes were reindexed in ~7 minutes. During indexing consumed 13% of the CPU and 4GB of RAM.

![image](https://user-images.githubusercontent.com/735878/171265789-5aaecbb4-cf57-4408-9ffc-7198903a4291.png)

After indexing is done, Obsidian doesn't consume CPU and still consumes 1.2GB of RAM.

**Comment by mnaoumov** [comment]
Another benefit of the storing index to the file, is helpful for using the plugin on mobile devices. Indexing there from scratch would be even more troublesome than on Desktop.

Also maybe if it makes sense to load cache from file only when requested to avoid eating the memory if the plugin is not used as often.

I am a software developer myself, so if I can be used in any capacity, do not hesitate.

**Comment by scambier** [comment]
>I am a software developer myself, so if I can be used in any capacity, do not hesitate.

Alright, so I'll lay things directly :)

Omnisearch uses [MiniSearch](https://github.com/lucaong/minisearch). It's an in-memory search engine, and I chose it mainly for 2 reasons:
- It's specifically built for frontend search, with a fast indexing and instant search results
- It supports on-the-fly document reindexing, which is quite useful if your documents change frequently, like in a note-taking app. 

The only downside is that it requires me to keep a raw copy of each note in-memory for reindexing, because Minisearch needs the original document to remove it from its index. Not an issue for most vaults, though.

As a reference, here are some stats from my dev vault : 
- 1300 notes
- Most notes are 1-2KB, the biggest ones are 12-13KB
- Total vault size (without attachments) is ~16MB
- Cold start indexing takes 2500-3500ms
- Peak memory usage at startup: ~300MB with Omnisearch, ~230MB without it
- Settled memory usage (10 seconds after startup): ~180MB with Omnisearch, ~160MB without it
- My CPU is a 6-core 3.6Ghz Ryzen

Indexing 40k files shouldn't take 7 minutes, nor should it consume 1.2GB-4GB of RAM. How big are your files and your vault? I suspect it's simply too large Omnisearch, or there's something else that's messing with it. What are the CPU & RAM usage without Omnisearch? How long does the core search plugin takes for indexing?

**Comment by scambier** [comment]
```mermaid
graph TD;
A(Is there a serialized index?) --Yes--> B(Load it from disk);
A --No--> C(Index at full speed);
C --> E(Serialize the index to disk);
B --> D(Minisearch instance);
C --> D;
```

That's all good, but how do we keep a serialized index up-to-date? 2 possibilities here:

1) Periodical full reindex

Having a slightly out-of-date index for 40k notes is acceptable (is it?).

Reindexing is done once in a while, either automatically (every x launches), or manually by the user, through a periodic popup reminder. I can also add a toggleable option to make the indexing slower.

Advantages :
- The heavy work is only done once in a while

Drawbacks:
- The index slowly becomes out-of-sync, until it's re-triggered

2) Incremental updates

Keeping the index up-to-date with fast incremental updates means keeping a copy of the original documents. So on top of the serialized index, we need to keep a serialized copy of all your notes. From that, we can keep the actual behavior where incremental updates are done when Obsidian is in the background.

The only issue is that if notes are modified outside of Obsidian, the index will be out-of-sync until it's rebuilt from scratch, or until the notes in question are modified in Obsidian.

Advantages :
- The index is (relatively) kept up-to-date

Drawbacks :
- Omnisearch needs a serialized copy of all your notes
- You still need to do a full reindex once in a while, if you happen to update files outside of Obsidian

---

Both solutions seem fine to me, but which one is the best totally depends on the vault. For my vault where notes often change, incremental updates are a must. For a huge vault of mostly static documents, it shouldn't make a difference.

**Comment by mnaoumov** [comment]
@scambier I accidentally found the reason for the high CPU usage. It has nothing to do with your plugin. It was caused by this bug: https://forum.obsidian.md/t/horrible-performance-if-explorer-pane-expanded-with-many-files/38471

After I collapsed my Explorer pane. The indexing time came down from 7 minutes to 5 minutes and CPU usage is nearly 0
