### ISSUE TITLE
[Feature request] Setting to hide the heading for a sleek clean look

### ISSUE THREAD

**Issue by akay64** [scambier/obsidian-omnisearch#67]
It would be nice to have a setting to hide the heading on the modal for a sleek clean look.

![image](https://user-images.githubusercontent.com/6232227/174491366-89e0bd93-8088-446f-9e0e-d64a8c4d84a9.png)

I have never worked on a Obsidian plugin before, but I will be happy learn to help add this if you agree.

**Comment by scambier** [comment]
👍 But since Omnisearch has 2 modals ("Vault" and "In-File"), I think it's important to still display this distinction somewhere. Maybe here?
![image](https://user-images.githubusercontent.com/3216752/174492548-9cdb642d-50fe-499f-b96e-7b8b49b5ea76.png)

If you're happy to help, I'll happily let you do it 😀 The settings are declared in `settings.ts` and the 2 modals are `ModalVault.svelte` and `ModalInFile.svelte`. It should be fairly straightforward, don't hesitate to ask if you need help. Thank you!

**Comment by akay64** [comment]
> 👍 But since Omnisearch has 2 modals ("Vault" and "In-File"), I think it's important to still display this distinction somewhere. Maybe here? ![image](https://user-images.githubusercontent.com/3216752/174492548-9cdb642d-50fe-499f-b96e-7b8b49b5ea76.png)
> 

Either that, or could use that placeholder area too "Type to search through your notes - Vault" and "Type to search through your notes - In-File"

**Comment by scambier** [comment]
Even better.
