### ISSUE TITLE
Bug: Trying to enable the plugin completely freezes Obsidian

### ISSUE THREAD

**Issue by chrisgrieser** [scambier/obsidian-omnisearch#7]
**Type of issue**

- [x] A bug
- [x] A performance problem

**Problem description**
Trying to enable the plugin completely freezes Obsidian. No console logs obtainable, cause Obsidian simply freezes. Restarting Obsidian lets Obsidian freeze at the startup screen. Only way to resolve this was to manually delete the plugin from the list of enabled plugins in `.obsidian/community-plugins.json`.

**Your environment**
```
macOS 12.2.1
Obsidian 0.14.2
```

Number of notes in your vault: 

```bash
# ran in vault root
find . -type f | wc -l
6338
```

Other plugins that may be related to the issue: 
None, I tried disabling all plugins, the issue still occurs.

**Comment by scambier** [comment]
Thanks for your report! I just released a fix in [0.1.2](https://github.com/scambier/obsidian-omnisearch/releases/tag/0.1.2) to let Obsidian breathe during the indexing. Let's hope it fixes the freeze.

**Comment by chrisgrieser** [comment]
nope, still freezes. 🙁

**Comment by scambier** [comment]
I tried with the help vault copy-pasted until I got nearly 10.000 notes. It takes 12 seconds to Omnisearch to index everything. I even reduced the "breathing room" period to the bare minimum, and there isn't any noticeable lag.

I suspect there's something in your notes that makes the indexing freeze...

Since it's totally freezing, the only way to fix this is to reduce the vault to pinpoint the file(s) that make Obsidian freeze, to somehow have a "minimum reproducible example". If you're able to do that, that would be awesome. I know you certainly have something else to do, but I can't reproduce this issue for now :/
The other solution would be to send me your vault so that I can experiment on it 🤷‍♂️

**Comment by garderobier** [comment]
I can confirm the freeze with 0.1.2 an obsidian 0.14.5

**Comment by Aaron-Bopp** [comment]
Just checked, and it also freezes on the Obsidian Hub vault, which you can [download and mess around with](https://github.com/obsidian-community/obsidian-hub/releases/tag/0.2.1)

Here's my environment
```
SYSTEM INFO:
	Obsidian version: v0.14.5
	Installer version: v0.13.24
	Operating system: Windows 10 Home 
```

**Comment by scambier** [comment]
Good news, this one also freezes for me!

**Comment by scambier** [comment]
Well it was easy 😅

The older dependency I used to convert markdown to plain text somehow crashed on some tables. I just had to replace it.

[Release 0.1.3](https://github.com/scambier/obsidian-omnisearch/releases/tag/0.1.3)
