### ISSUE TITLE
[Feature request] Search for settings & commands

### ISSUE THREAD

**Issue by asafarevich** [scambier/obsidian-omnisearch#98]
**Is your feature request related to a problem? Please describe.**
Wish it worked similar to jetbrains software  where you could search settings, actions, etc...  See screenshot below. In this screenshot. I can switch between search contexts with tab (similar to omnisearch, but it is visible which context I'm on and other options available)

**Describe the solution you'd like**

when doing omnisearch, indicator on top on which type of search doing. (such as file/entire system/settings/actions)

**Describe alternatives you've considered**

separate shortcut keys for different searchs. However this is cumbersome.

**Additional context**

![image](https://user-images.githubusercontent.com/30283914/191098652-0d9cde46-6106-4fca-9bd9-04d1a7eac812.png)

**Comment by Anton-Velikodnyy** [comment]
Maybe to add... Filter tabs that would be useful to switch between
1. All (default omnisearch behavior)
2. Current FIle (already existsin in omnisearch)
3. File Names (open quick switcher exists, but would be great if under one umbrellal)
4. Settings (not sure how feasable it is, since not much comes up for setting navigation with keyboard)
5. Actions (open command pallete)

**Comment by scambier** [comment]
Related discussion: https://github.com/scambier/obsidian-omnisearch/discussions/31

**Comment by scambier** [comment]
I'd rather keep Omnisearch focused on documents retrieval, there's enough work on that front.
